ktor:
  deployment:
    port: "$APPLICATION_PORT:8080"
  application:
    modules:
      - org.maxkizi.regiondict.ApplicationKt.module

datasource:
  url: "$DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432/region_dict"
  username: "$DATASOURCE_USERNAME:postgres"
  password: "$DATASOURCE_PASSWORD:postgres"

#repo: jdbc
repo: "$REPO_MODE:jdbc"