ktor:
  deployment:
    port: 8080
  application:
    modules:
      - org.maxkizi.regiondict.ApplicationKt.module

datasource:
  url: "jdbc:postgresql://localhost:5432/region_dict"
  username: postgres
  password: postgres

#repo: jdbc
repo: in-memory